apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: example
spec:
  steps:
    - try:
        - script:
            timeout: 5m
            content: |
              kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/v3.16.3/deploy/gatekeeper.yaml
        - script:
            timeout: 5m
            content: |
              kubectl wait --for=condition=Available deploy/gatekeeper-audit -n gatekeeper-system --timeout=3m
        - script:
            timeout: 5m
            content: |
              kubectl wait --for=condition=Available deploy/gatekeeper-controller-manager -n gatekeeper-system --timeout=3m
        - apply:
            file: mutation-config.yaml
        - apply:
            file: pod.yaml
        - assert:
            file: podmodified.yaml
      cleanup:
        - script:
            timeout: 10m
            content: |
              kubectl delete -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/v3.16.3/deploy/gatekeeper.yaml
      catch:
        - script:
            timeout: 5m
            content: |
              kubectl get po -n gatekeeper-system
            check:
              # This check ensures that the string '1.28' is found
              # in stdout or else fails
              (contains($stdout, 'gatekeeper')): true
