apiVersion: v1
kind: Pod
metadata:
  name: test-kuttl
  namespace: default
spec:
  containers:
    - image: nginx:alpine
      name: nginx
      securityContext:
        allowPrivilegeEscalation: false
